import { listUsers } from "@/actions/auth";
import { getPublishReady, publishQuestion as publishQuestionAction } from "@/actions/publish";
import { addProjectMember as addProjectMemberAction, createProject as createProjectAction, getProject as getProjectAction, listProjectMembers as listProjectMembersAction, listProjects, updateProject as updateProjectAction } from "@/actions/projects";
import { listQuestions } from "@/actions/questions";
import { getReviewQueue as getReviewQueueAction } from "@/actions/review";
import { getTaxonomy as getTaxonomyAction } from "@/actions/taxonomy";
import { callAction } from "./client";

export type TaxonomyItem = {
  id: string;
  name: string;
  code: string;
  status: string;
  subjectId?: string;
  chapterId?: string;
  slug?: string;
  kind?: string;
  aliases?: string[];
  scope?: string | null;
  includes?: string[];
  excludes?: string[];
  overlaps?: string[];
  referenceSections?: string[];
  estimatedTopics?: number | null;
  relatedTopics?: string[];
  secondarySubjects?: string[];
};
export type Taxonomy = { subjects: TaxonomyItem[]; chapters: TaxonomyItem[]; topics: TaxonomyItem[]; difficulties: TaxonomyItem[]; exams: TaxonomyItem[]; questionTypes: TaxonomyItem[] };
export type Project = { id: string; name: string; examId: string; year: number; session: string | null; status: "active" | "archived"; templateCode: string; targetQuestionCount: number | null; deadline: string | null; projectLeadProfileId: string | null; createdBy: string; createdAt: string; updatedAt: string };
export type ProjectListItem = { project: Project; exam: TaxonomyItem; memberRole: string | null };
export type ProjectDetails = { project: Project; exam: TaxonomyItem };
export type ProjectMember = { member: { id: string; projectRole: string; status: string; joinedAt: string }; profile: { id: string; displayName: string; email: string; status: string } };
export type QuestionRow = { question: { id: string; publicQid: string; questionNumber: number; status: string; projectId: string; createdBy: string }; revision: { id: string; stem: string; subjectId: string; topicId: string; chapterId: string } };
export type ReviewQueueItem = { item: { id: string; status: string }; question: { id: string }; revision: { id: string } };
export type StudioProfile = { id: string; displayName: string; email: string; status: string };
export type PublishReadyItem = { question: { id: string; publicQid: string; status: string }; revision: { id: string; revisionNumber: number; status: string; stem: string } };

export const getProjects = () => callAction<ProjectListItem[]>(listProjects());
export const getProject = (projectId: string) => callAction<ProjectDetails>(getProjectAction(projectId));
export const getProjectMembers = (projectId: string) => callAction<ProjectMember[]>(listProjectMembersAction(projectId));
export const getTaxonomy = () => callAction<Taxonomy>(getTaxonomyAction());
export const getQuestions = (params: Record<string, string | number | undefined>) => callAction<QuestionRow[]>(listQuestions(params));
export const getReviewQueue = () => callAction<ReviewQueueItem[]>(getReviewQueueAction());
export const createProject = (body: { name: string; examId: string; year: number; session?: string }) => callAction<Project>(createProjectAction(body));
export const getStudioUsers = () => callAction<StudioProfile[]>(listUsers());
export const getPublishReadyQuestions = () => callAction<PublishReadyItem[]>(getPublishReady());
export const publishQuestion = (questionId: string) => callAction<unknown>(publishQuestionAction(questionId));
export const addProjectMember = (projectId: string, body: { profileId: string; projectRole: string }) => callAction<ProjectMember>(addProjectMemberAction(projectId, body));
export const updateProject = (projectId: string, body: { name?: string; session?: string | null; status?: "active" | "archived" }) => callAction<Project>(updateProjectAction(projectId, body));
