import { studioFetch } from "./client";

export type TaxonomyItem = {
  id: string;
  name: string;
  code: string;
  status: string;
  subjectId?: string;
  chapterId?: string;
  slug?: string;
  kind?: string;
  aliases?: string[];
  scope?: string | null;
  includes?: string[];
  excludes?: string[];
  overlaps?: string[];
  referenceSections?: string[];
  estimatedTopics?: number | null;
  relatedTopics?: string[];
  secondarySubjects?: string[];
};
export type Taxonomy = { subjects: TaxonomyItem[]; chapters: TaxonomyItem[]; topics: TaxonomyItem[]; difficulties: TaxonomyItem[]; exams: TaxonomyItem[]; questionTypes: TaxonomyItem[] };
export type Project = { id: string; name: string; examId: string; year: number; session: string | null; status: "active" | "archived"; templateCode: string; targetQuestionCount: number | null; deadline: string | null; projectLeadProfileId: string | null; createdBy: string; createdAt: string; updatedAt: string };
export type ProjectListItem = { project: Project; exam: TaxonomyItem; memberRole: string | null };
export type ProjectDetails = { project: Project; exam: TaxonomyItem };
export type ProjectMember = { member: { id: string; projectRole: string; status: string; joinedAt: string }; profile: { id: string; displayName: string; email: string; status: string } };
export type QuestionRow = { question: { id: string; publicQid: string; questionNumber: number; status: string; projectId: string; createdBy: string }; revision: { id: string; stem: string; subjectId: string; topicId: string; chapterId: string } };
export type ReviewQueueItem = { item: { id: string; status: string }; question: { id: string }; revision: { id: string } };
export type StudioProfile = { id: string; displayName: string; email: string; status: string };
export type PublishReadyItem = { question: { id: string; publicQid: string; status: string }; revision: { id: string; revisionNumber: number; status: string; stem: string } };
export const getProjects = () => studioFetch<ProjectListItem[]>("/projects");
export const getProject = (projectId: string) => studioFetch<ProjectDetails>(`/projects/${projectId}`);
export const getProjectMembers = (projectId: string) => studioFetch<ProjectMember[]>(`/projects/${projectId}/members`);
export const getTaxonomy = () => studioFetch<Taxonomy>("/taxonomy");
export const getQuestions = (params: Record<string, string | number | undefined>) => studioFetch<QuestionRow[]>(`/questions?${new URLSearchParams(Object.entries(params).filter((entry): entry is [string, string] => entry[1] !== undefined).map(([key, value]) => [key, String(value)])).toString()}`);
export const getReviewQueue = () => studioFetch<ReviewQueueItem[]>("/review/queue");
export const createProject = (body: { name: string; examId: string; year: number; session?: string }) => studioFetch<Project>("/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
export const getStudioUsers = () => studioFetch<StudioProfile[]>("/users");
export const getPublishReadyQuestions = () => studioFetch<PublishReadyItem[]>("/publish/ready");
export const publishQuestion = (questionId: string) => studioFetch<unknown>(`/questions/${questionId}/publish`, { method: "POST" });
export const addProjectMember = (projectId: string, body: { profileId: string; projectRole: string }) => studioFetch<ProjectMember>(`/projects/${projectId}/members`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
export const updateProject = (projectId: string, body: { name?: string; session?: string | null; status?: "active" | "archived" }) => studioFetch<Project>(`/projects/${projectId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
