import { studioFetch } from "./client";
export type QueueItem = { item: { id: string; queueId: string; status: string }; question: { id: string; publicQid: string; status: string }; revision: { id: string; stem: string; requiresMedicalReview: "yes" | "no" }; previousItemId: string | null; nextItemId: string | null };
export type Comment = { comment: { id: string; body: string; createdAt: string; revisionId: string | null }; author: { id: string; displayName: string; email: string } };
export const getReviewQueue = () => studioFetch<{ queue: { id: string }; items: QueueItem[] }>("/review/queue");
export const getReviewItem = (questionId: string) => studioFetch<{ question: { id: string; publicQid: string; status: string }; revision: { id: string; stem: string; requiresMedicalReview: "yes" | "no" }; options: { label: string; content: string }[] }>(`/review/items/${questionId}`);
export const getComments = (questionId: string) => studioFetch<Comment[]>(`/questions/${questionId}/comments`);
export const addComment = (questionId: string, body: string, revisionId?: string) => studioFetch<Comment>(`/questions/${questionId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body, revisionId }) });
export const approveQuestion = (questionId: string) => studioFetch<unknown>(`/questions/${questionId}/review/approve`, { method: "POST" });
export const requestChanges = (questionId: string, comment: string) => studioFetch<unknown>(`/questions/${questionId}/review/request-changes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ comment }) });
export const skipQueueItem = (queueId: string) => studioFetch<unknown>(`/review/queue/${queueId}/skip`, { method: "POST" });
