import type { SourceBatch } from './types.js';
export type MigrationExam = 'neet-pg' | 'upsc-cms';
export const sourceBatches: SourceBatch[] = [
  { year: 2020, set: null, subjects: [] }, { year: 2021, set: null, subjects: [] }, { year: 2022, set: null, subjects: [] }, { year: 2023, set: null, subjects: [] }, { year: 2024, set: 1, subjects: [] }, { year: 2024, set: 2, subjects: [] }, { year: 2025, set: null, subjects: [] },
];
export const upscSourceBatches: SourceBatch[] = [
  { year: 2018, set: null, subjects: [] }, { year: 2019, set: null, subjects: [] }, { year: 2020, set: null, subjects: [] }, { year: 2021, set: null, subjects: [] }, { year: 2022, set: null, subjects: [] }, { year: 2023, set: null, subjects: [] }, { year: 2024, set: null, subjects: [] }, { year: 2025, set: null, subjects: [] }, { year: 2026, set: null, subjects: [] },
];
export const subjectNameMap: Record<string, string> = { Anatomy: 'Anatomy', Physiology: 'Physiology', Biochemistry: 'Biochemistry', Pathology: 'Pathology', Microbiology: 'Microbiology', Pharmacology: 'Pharmacology', ENT: 'Otorhinolaryngology', Ophthalmology: 'Ophthalmology', 'Community Medicine': 'Community Medicine', 'Forensic Medicine': 'Forensic Medicine & Toxicology', Psychiatry: 'Psychiatry', Anesthesia: 'Anaesthesia', Dermatology: 'Dermatology', Pediatrics: 'Paediatrics', Orthopedics: 'Orthopaedics', Radiology: 'Radiology', Medicine: 'Medicine', Surgery: 'Surgery', OBG: 'Obstetrics & Gynaecology' };
export const questionTypeCodeMap: Record<string, string> = { 'side effects/drug interaction': 'side_effects', side_effects_drug_interaction: 'side_effects', clinical_staging_and_classification: 'classification_and_staging', image_based: 'image_based', 'Image-Based': 'image_based', clinical_reasoning: 'clinical_reasoning', 'clinical reasoning': 'clinical_reasoning', 'Clinical Reasoning': 'clinical_reasoning', 'clinical reasoning / image-based': 'clinical_reasoning', assertion_reason: 'assertion_reason', match_the_following: 'match_the_following', direct_recall: 'direct_recall', 'Direct Recall': 'direct_recall', conceptual: 'conceptual', 'Conceptual Understanding': 'conceptual', 'conceptual understanding': 'conceptual', numerical: 'numerical', Numerical: 'numerical', mechanism_of_action: 'mechanism_of_action', clinical_diagnosis: 'clinical_diagnosis', clinical_management: 'clinical_management', classification_and_staging: 'classification_and_staging', classification_staging: 'classification_and_staging', 'classification staging': 'classification_and_staging', 'Classification and Staging': 'classification_and_staging', staging_and_classification: 'classification_and_staging', staging: 'staging', side_effects: 'side_effects', clinical_complications: 'clinical_complications', clinical_complication: 'clinical_complications', clinical_correlation: 'clinical_correlation', clinical_pathological_correlation: 'clinical_pathological_correlation', instruments: 'instruments', instrumental: 'instruments', named_tests: 'named_tests', treatment_protocol: 'treatment_protocol', graph_based: 'graph_based', biochemical_correlation: 'biochemical_correlation', clinical_genetic_correlation: 'clinical_genetic_correlation', clinical_syndromes: 'clinical_syndromes', clinical_finding: 'clinical_finding', clinical_physiology: 'clinical_physiology', 'clinical_diagnosis_&_management': 'clinical_diagnosis_management' };
export const MIGRATION_PROFILE_ID = '00000000-0000-4000-8000-000000000001';
export const MIGRATION_PROFILE_EMAIL = 'migration@pyqs.local';
export function publicQid(exam: MigrationExam, year: number, set: number | null, subject: string, index: number) { return `${exam === 'neet-pg' ? 'NEETPG' : 'UPSCCMS'}-${year}${set ? `-SET${set}` : ''}-${subject.toUpperCase().replace(/[^A-Z0-9]+/g, '-')}-${String(index + 1).padStart(3, '0')}`; }
