import { asc, eq } from 'drizzle-orm';
import { db } from '../../database/client.js';
import { studioAuditLog, studioExplanationBlock, studioQuestion, studioQuestionRevision, studioReference } from '../../database/schema.js';
import type { AddBlock, ReplaceBlocks, ReplaceReferences, UpdateBlock } from './explanations.schemas.js';

export class ExplanationsRepository {
  list(revisionId: string) { return db.select().from(studioExplanationBlock).where(eq(studioExplanationBlock.revisionId, revisionId)).orderBy(asc(studioExplanationBlock.position)); }
  async findBlock(blockId: string) { const [row] = await db.select({ block: studioExplanationBlock, question: studioQuestion, revision: studioQuestionRevision }).from(studioExplanationBlock).innerJoin(studioQuestionRevision, eq(studioExplanationBlock.revisionId, studioQuestionRevision.id)).innerJoin(studioQuestion, eq(studioQuestionRevision.questionId, studioQuestion.id)).where(eq(studioExplanationBlock.id, blockId)); return row ?? null; }
  async replace(revisionId: string, questionId: string, input: ReplaceBlocks, profileId: string) { return db.transaction(async (tx) => { await tx.delete(studioExplanationBlock).where(eq(studioExplanationBlock.revisionId, revisionId)); const rows = input.blocks.length ? await tx.insert(studioExplanationBlock).values(input.blocks.map((block) => ({ ...block, revisionId, createdBy: profileId }))).returning() : []; await tx.update(studioQuestionRevision).set({ requiresMedicalReview: 'yes', medicalReviewedBy: null, medicalReviewedAt: null }).where(eq(studioQuestionRevision.id, revisionId)); await tx.insert(studioAuditLog).values({ questionId, revisionId, actorProfileId: profileId, action: 'explanation_blocks_saved', metadata: { blockCount: rows.length } }); return rows; }); }
  async add(revisionId: string, questionId: string, input: AddBlock, profileId: string) { return db.transaction(async (tx) => { const existing = await tx.select({ id: studioExplanationBlock.id }).from(studioExplanationBlock).where(eq(studioExplanationBlock.revisionId, revisionId)); const [block] = await tx.insert(studioExplanationBlock).values({ ...input, revisionId, position: existing.length, createdBy: profileId }).returning(); await tx.insert(studioAuditLog).values({ questionId, revisionId, actorProfileId: profileId, action: 'explanation_block_added', metadata: { blockId: block!.id } }); return block!; }); }
  async update(blockId: string, questionId: string, revisionId: string, input: UpdateBlock, profileId: string) { return db.transaction(async (tx) => { const [block] = await tx.update(studioExplanationBlock).set(input).where(eq(studioExplanationBlock.id, blockId)).returning(); if (!block) return null; await tx.insert(studioAuditLog).values({ questionId, revisionId, actorProfileId: profileId, action: 'explanation_block_updated', metadata: { blockId } }); return block; }); }
  async remove(blockId: string, questionId: string, revisionId: string, profileId: string) { return db.transaction(async (tx) => { const [block] = await tx.delete(studioExplanationBlock).where(eq(studioExplanationBlock.id, blockId)).returning(); if (!block) return null; const remaining = await tx.select().from(studioExplanationBlock).where(eq(studioExplanationBlock.revisionId, revisionId)).orderBy(asc(studioExplanationBlock.position)); for (const [position, item] of remaining.entries()) await tx.update(studioExplanationBlock).set({ position }).where(eq(studioExplanationBlock.id, item.id)); await tx.insert(studioAuditLog).values({ questionId, revisionId, actorProfileId: profileId, action: 'explanation_block_deleted', metadata: { blockId } }); return block; }); }
  listReferences(revisionId: string) { return db.select().from(studioReference).where(eq(studioReference.revisionId, revisionId)).orderBy(asc(studioReference.position)); }
  async replaceReferences(revisionId: string, questionId: string, input: ReplaceReferences, profileId: string) { return db.transaction(async (tx) => { await tx.delete(studioReference).where(eq(studioReference.revisionId, revisionId)); const rows = input.references.length ? await tx.insert(studioReference).values(input.references.map((reference) => ({ ...reference, revisionId, createdBy: profileId }))).returning() : []; await tx.update(studioQuestionRevision).set({ requiresMedicalReview: 'yes', medicalReviewedBy: null, medicalReviewedAt: null }).where(eq(studioQuestionRevision.id, revisionId)); await tx.insert(studioAuditLog).values({ questionId, revisionId, actorProfileId: profileId, action: 'references_saved', metadata: { referenceCount: rows.length } }); return rows; }); }
}
export const explanationsRepository = new ExplanationsRepository();
