"use client";
import { useQuery } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/shared/page-header";
import { ContentSkeleton, EmptyState, ErrorState } from "@/components/shared/state-panels";
import { StatusBadge } from "@/components/shared/status-badge";
import { getProject, getQuestions, getTaxonomy } from "@/lib/api/projects";
export default function SubjectWorkspacePage() { const { projectId, subjectId } = useParams<{ projectId: string; subjectId: string }>(); const project = useQuery({ queryKey: ["projects", projectId], queryFn: () => getProject(projectId) }); const taxonomy = useQuery({ queryKey: ["taxonomy"], queryFn: getTaxonomy, staleTime: 300_000 }); const questions = useQuery({ queryKey: ["questions", { projectId, subjectId }], queryFn: () => getQuestions({ projectId, subjectId, limit: 100 }) }); if (project.isLoading || taxonomy.isLoading || questions.isLoading) return <ContentSkeleton rows={6} />; if (project.isError || taxonomy.isError || questions.isError || !project.data || !taxonomy.data || !questions.data) return <ErrorState description="We couldn't load this subject workspace." onRetry={() => { void project.refetch(); void taxonomy.refetch(); void questions.refetch(); }} />; const subject = taxonomy.data.subjects.find((item) => item.id === subjectId); return <><PageHeader eyebrow={project.data.project.name} title={subject?.name ?? "Subject workspace"} description="Project, exam, year, and subject context are retained here." actions={<Button disabled title="Question entry arrives in Phase 4"><Plus className="size-4" />Add question</Button>} />{questions.data.length === 0 ? <EmptyState title="No questions in this subject" description="Add the first question once the fast authoring workflow is enabled in Phase 4." /> : <section className="overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="min-w-[680px] w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs font-medium uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">QID</th><th className="px-5 py-3">Question</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{questions.data.map(({ question, revision }) => <tr key={question.id} className="border-b last:border-0"><td className="px-5 py-4 font-mono text-xs text-slate-600">{question.publicQid}</td><td className="max-w-xl px-5 py-4"><Link className="font-medium hover:underline" href={`/questions/${question.id}`}>{revision.stem}</Link></td><td className="px-5 py-4"><StatusBadge status={question.status} /></td></tr>)}</tbody></table></div></section>}</>; }
