import { Router, type Router as ExpressRouter } from 'express';
import { asyncHandler } from '../../lib/async-handler.js';
import { requireStudioAuth } from '../../middleware/require-studio-auth.middleware.js';
import { validateRequest } from '../../middleware/validate.middleware.js';
import { questionsController } from './questions.controller.js';
import { createQuestionSchema, duplicateQuestionSchema, projectSubjectParamsSchema, questionIdParamsSchema, questionListQuerySchema, revisionIdParamsSchema, revisionNumberParamsSchema, revisionParamsSchema, updateDraftSchema } from './questions.schemas.js';
export const questionsRouter: ExpressRouter = Router();
export const questionWorkspaceRouter: ExpressRouter = Router();
export const questionRevisionsRouter: ExpressRouter = Router();
questionsRouter.use(requireStudioAuth);
questionWorkspaceRouter.use(requireStudioAuth);
questionRevisionsRouter.use(requireStudioAuth);
questionsRouter.get('/', validateRequest({ query: questionListQuerySchema }), asyncHandler((req, res) => questionsController.list(req, res)));
questionsRouter.get('/:questionId', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.get(req, res)));
questionsRouter.get('/:questionId/contributors', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.contributors(req, res)));
questionsRouter.get('/:questionId/audit-log', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.auditLog(req, res)));
questionsRouter.get('/:questionId/revisions', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.listRevisions(req, res)));
questionsRouter.get('/:questionId/revisions/:revisionNumber', validateRequest({ params: revisionNumberParamsSchema }), asyncHandler((req, res) => questionsController.getRevision(req, res)));
questionsRouter.post('/:questionId/revisions', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.createRevision(req, res)));
questionsRouter.patch('/:questionId/revisions/:revisionId/draft', validateRequest({ params: revisionParamsSchema, body: updateDraftSchema }), asyncHandler((req, res) => questionsController.saveDraft(req, res)));
questionsRouter.post('/:questionId/duplicate', validateRequest({ params: questionIdParamsSchema, body: duplicateQuestionSchema }), asyncHandler((req, res) => questionsController.duplicate(req, res)));
questionsRouter.post('/:questionId/submit', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.submit(req, res)));
questionsRouter.post('/:questionId/archive', validateRequest({ params: questionIdParamsSchema }), asyncHandler((req, res) => questionsController.archive(req, res)));
questionWorkspaceRouter.post('/projects/:projectId/subjects/:subjectId/questions', validateRequest({ params: projectSubjectParamsSchema, body: createQuestionSchema }), asyncHandler((req, res) => questionsController.create(req, res)));
questionWorkspaceRouter.get('/projects/:projectId/subjects/:subjectId/questions', validateRequest({ params: projectSubjectParamsSchema, query: questionListQuerySchema }), asyncHandler((req, res) => questionsController.listProjectSubject(req, res)));
questionRevisionsRouter.patch('/question-revisions/:revisionId/draft', validateRequest({ params: revisionIdParamsSchema, body: updateDraftSchema }), asyncHandler((req, res) => questionsController.saveDraftByRevision(req, res)));
questionRevisionsRouter.patch('/question-revisions/:revisionId', validateRequest({ params: revisionIdParamsSchema, body: updateDraftSchema }), asyncHandler((req, res) => questionsController.saveDraftByRevision(req, res)));
questionRevisionsRouter.post('/question-revisions/:revisionId/validate', validateRequest({ params: revisionIdParamsSchema }), asyncHandler((req, res) => questionsController.validateRevision(req, res)));
