import crypto from 'node:crypto';
import { AppError } from '../../lib/AppError.js';
import { projectsService } from '../projects/projects.service.js';
import type { StudioSession } from '../auth/auth.types.js';
import { questionsRepository } from './questions.repository.js';
import { taxonomyRepository } from '../taxonomy/taxonomy.repository.js';
import type { QuestionDraftInput } from './questions.schemas.js';

export class QuestionsService {
  async create(projectId: string, subjectId: string, input: QuestionDraftInput, session: StudioSession) { if (!session.permissions.includes('question.create')) throw new AppError({ statusCode: 403, code: 'PERMISSION_DENIED', message: 'You do not have permission to create questions.' }); await projectsService.get(projectId, session); await this.validateHierarchy(subjectId, input); return questionsRepository.create(input, projectId, subjectId, session.profileId, `PYQS-${crypto.randomUUID().replaceAll('-', '').toUpperCase()}`); }
  async get(questionId: string, session: StudioSession) { const details = await questionsRepository.details(questionId); if (!details) throw new AppError({ statusCode: 404, code: 'QUESTION_NOT_FOUND', message: 'Question not found.' }); await projectsService.get(details.question.projectId, session); return details; }
  async createRevision(questionId: string, session: StudioSession) { const question = await questionsRepository.find(questionId); if (!question) throw new AppError({ statusCode: 404, code: 'QUESTION_NOT_FOUND', message: 'Question not found.' }); await projectsService.get(question.projectId, session); if (!session.permissions.includes('question.edit') && question.createdBy !== session.profileId) throw new AppError({ statusCode: 403, code: 'PERMISSION_DENIED', message: 'You do not have permission to edit this question.' }); const revision = await questionsRepository.createRevision(questionId, session.profileId); if (!revision) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); return revision; }
  async saveDraft(questionId: string, revisionId: string, input: QuestionDraftInput, session: StudioSession) { const question = await questionsRepository.find(questionId); if (!question) throw new AppError({ statusCode: 404, code: 'QUESTION_NOT_FOUND', message: 'Question not found.' }); await projectsService.get(question.projectId, session); if (!session.permissions.includes('question.edit') && question.createdBy !== session.profileId) throw new AppError({ statusCode: 403, code: 'PERMISSION_DENIED', message: 'You do not have permission to edit this question.' }); if (!await questionsRepository.findRevision(questionId, revisionId)) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); return questionsRepository.updateDraft(questionId, revisionId, input, session.profileId); }
  private async validateHierarchy(subjectId: string, input: QuestionDraftInput) { const [chapter, topic] = await Promise.all([taxonomyRepository.findChapter(input.chapterId), taxonomyRepository.findTopic(input.topicId)]); if (!chapter || chapter.status !== 'active' || chapter.subjectId !== subjectId) throw new AppError({ statusCode: 400, code: 'INVALID_CHAPTER', message: 'Chapter must belong to the selected active subject.' }); if (!topic || topic.status !== 'active' || topic.chapterId !== chapter.id) throw new AppError({ statusCode: 400, code: 'INVALID_TOPIC', message: 'Topic must belong to the selected active chapter.' }); }
}
export const questionsService = new QuestionsService();
