import crypto from 'node:crypto';
import { AppError } from '../../lib/AppError.js';
import { projectsService } from '../projects/projects.service.js';
import { projectsRepository } from '../projects/projects.repository.js';
import type { StudioSession } from '../auth/auth.types.js';
import { questionsRepository } from './questions.repository.js';
import { taxonomyRepository } from '../taxonomy/taxonomy.repository.js';
import type { QuestionDraftInput } from './questions.schemas.js';
import type { QuestionListQuery } from './questions.schemas.js';

const EDITABLE_REVISION_STATUS = 'DRAFT';
const SUBMITTABLE_STATUSES = new Set(['DRAFT', 'CHANGES_REQUESTED']);

export class QuestionsService {
  async list(query: QuestionListQuery, session: StudioSession) {
    if (query.projectId) await projectsService.get(query.projectId, session);
    const accessibleProjectIds = session.permissions.includes('question.view_all') ? null : (await projectsService.list(session)).map((row) => row.project.id);
    return questionsRepository.list(query, accessibleProjectIds);
  }
  async create(projectId: string, subjectId: string, input: QuestionDraftInput, session: StudioSession) { if (!session.permissions.includes('question.create')) throw new AppError({ statusCode: 403, code: 'PERMISSION_DENIED', message: 'You do not have permission to create questions.' }); await projectsService.get(projectId, session); await this.validateHierarchy(subjectId, input); return questionsRepository.create(input, projectId, subjectId, session.profileId, `PYQS-${crypto.randomUUID().replaceAll('-', '').toUpperCase()}`); }
  async get(questionId: string, session: StudioSession) { const details = await questionsRepository.details(questionId); if (!details) throw new AppError({ statusCode: 404, code: 'QUESTION_NOT_FOUND', message: 'Question not found.' }); await projectsService.get(details.question.projectId, session); return details; }
  async listContributors(questionId: string, session: StudioSession) { await this.requireQuestionAccess(questionId, session); return questionsRepository.listContributors(questionId); }
  async listAuditLogs(questionId: string, session: StudioSession) { await this.requireQuestionAccess(questionId, session); return questionsRepository.listAuditLogs(questionId); }
  async listRevisions(questionId: string, session: StudioSession) { await this.requireQuestionAccess(questionId, session); return questionsRepository.listRevisions(questionId); }
  async getRevision(questionId: string, revisionNumber: number, session: StudioSession) { await this.requireQuestionAccess(questionId, session); const revision = await questionsRepository.findRevisionByNumber(questionId, revisionNumber); if (!revision) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); return revision; }
  async createRevision(questionId: string, session: StudioSession) { const question = await this.requireQuestionAccess(questionId, session); await this.requireEdit(question, session); if (question.status === 'ARCHIVED') throw new AppError({ statusCode: 409, code: 'QUESTION_ARCHIVED', message: 'An archived question cannot be revised.' }); const revision = await questionsRepository.createRevision(questionId, session.profileId); if (!revision) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); return revision; }
  async saveDraft(questionId: string, revisionId: string, input: QuestionDraftInput, session: StudioSession) { const question = await this.requireQuestionAccess(questionId, session); await this.requireEdit(question, session); const revision = await questionsRepository.findRevision(questionId, revisionId); if (!revision) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); this.requireEditableRevision(revision.status); await this.validateHierarchy(revision.subjectId, input); return questionsRepository.updateDraft(questionId, revisionId, input, session.profileId); }
  async saveDraftByRevision(revisionId: string, input: QuestionDraftInput, session: StudioSession) { const item = await questionsRepository.findByRevisionId(revisionId); if (!item) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); return this.saveDraft(item.question.id, revisionId, input, session); }
  async duplicate(questionId: string, input: { projectId?: string | undefined }, session: StudioSession) { const source = await this.requireQuestionAccess(questionId, session); await this.requireEdit(source, session); const targetProjectId = input.projectId ?? source.projectId; await projectsService.get(targetProjectId, session); return questionsRepository.duplicate(questionId, targetProjectId, session.profileId, `PYQS-${crypto.randomUUID().replaceAll('-', '').toUpperCase()}`); }
  async submit(questionId: string, session: StudioSession) { const question = await this.requireQuestionAccess(questionId, session); await this.requireEdit(question, session); if (!SUBMITTABLE_STATUSES.has(question.status)) throw new AppError({ statusCode: 409, code: 'INVALID_WORKFLOW_TRANSITION', message: `Question in ${question.status} cannot be submitted.` }); const latest = (await questionsRepository.listRevisions(questionId))[0]; if (!latest) throw new AppError({ statusCode: 409, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question has no revision to submit.' }); this.requireEditableRevision(latest.status); const validation = await this.validateRevision(questionId, session); if (validation.errors.length) throw new AppError({ statusCode: 400, code: 'QUESTION_VALIDATION_FAILED', message: 'Question must pass validation before submission.', details: validation }); return questionsRepository.updateQuestionStatus(questionId, 'QUESTION_SUBMITTED', session.profileId, 'question_submitted'); }
  async archive(questionId: string, session: StudioSession) { const question = await this.requireQuestionAccess(questionId, session); await this.requireEdit(question, session); if (question.status === 'PUBLISHED') throw new AppError({ statusCode: 409, code: 'PUBLISHED_QUESTION_ARCHIVE_BLOCKED', message: 'Published questions require an explicit unpublish policy before archiving.' }); if (question.status === 'ARCHIVED') return question; return questionsRepository.updateQuestionStatus(questionId, 'ARCHIVED', session.profileId, 'question_archived'); }
  async validateRevision(revisionId: string, session: StudioSession) { const item = await questionsRepository.findByRevisionId(revisionId); if (!item) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); await this.requireQuestionAccess(item.question.id, session); const [revisionDetails, revisions] = await Promise.all([questionsRepository.revisionDetails(item.question.id, revisionId), questionsRepository.listRevisions(item.question.id)]); const errors: Array<{ field: string; message: string }> = []; if (!item.revision.stem.trim()) errors.push({ field: 'stem', message: 'Question stem is required.' }); if (!['A', 'B', 'C', 'D'].includes(item.revision.correctOption)) errors.push({ field: 'correctOption', message: 'Correct option must be A, B, C, or D.' }); if (!revisionDetails || revisionDetails.options.length !== 4 || new Set(revisionDetails.options.map((option) => option.label)).size !== 4) errors.push({ field: 'options', message: 'Exactly four uniquely labelled options are required.' }); if (!revisionDetails || revisionDetails.questionTypes.length === 0) errors.push({ field: 'questionTypeIds', message: 'At least one question type is required.' }); return { valid: errors.length === 0, errors, warnings: [], revisionId, questionId: item.question.id, revisionNumber: item.revision.revisionNumber, revisionCount: revisions.length }; }
  async requireQuestionAccess(questionId: string, session: StudioSession) { const question = await questionsRepository.find(questionId); if (!question) throw new AppError({ statusCode: 404, code: 'QUESTION_NOT_FOUND', message: 'Question not found.' }); await projectsService.get(question.projectId, session); return question; }
  private async requireEdit(question: { projectId: string; createdBy: string }, session: StudioSession) { if (session.permissions.includes('question.edit') || question.createdBy === session.profileId) return; const member = await projectsRepository.findMembership(question.projectId, session.profileId); if (member && ['project_owner', 'project_admin', 'tutor'].includes(member.projectRole)) return; throw new AppError({ statusCode: 403, code: 'PERMISSION_DENIED', message: 'You do not have permission to edit this question.' }); }
  private requireEditableRevision(status: string) { if (status !== EDITABLE_REVISION_STATUS) throw new AppError({ statusCode: 409, code: 'IMMUTABLE_REVISION', message: 'Only draft revisions can be edited.' }); }
  private async validateHierarchy(subjectId: string, input: QuestionDraftInput) { const [chapter, topic] = await Promise.all([taxonomyRepository.findChapter(input.chapterId), taxonomyRepository.findTopic(input.topicId)]); if (!chapter || chapter.status !== 'active' || chapter.subjectId !== subjectId) throw new AppError({ statusCode: 400, code: 'INVALID_CHAPTER', message: 'Chapter must belong to the selected active subject.' }); if (!topic || topic.status !== 'active' || topic.chapterId !== chapter.id) throw new AppError({ statusCode: 400, code: 'INVALID_TOPIC', message: 'Topic must belong to the selected active chapter.' }); }
}
export const questionsService = new QuestionsService();
