import "server-only";

import type { StudioSession } from "@/lib/api/types";
import { AppError } from "@/server/lib/AppError";
import { questionsRepository } from "@/server/repositories/questions.repository";
import { questionsService } from "@/server/services/questions.service";
import type { AddBlock, ReplaceBlocks, ReplaceReferences, UpdateBlock } from "@/server/schemas/explanations.schemas";
import { explanationsRepository } from "@/server/repositories/explanations.repository";

export class ExplanationsService {
  async list(questionId: string, revisionId: string, session: StudioSession) { await this.requireRevision(questionId, revisionId, session); return explanationsRepository.list(revisionId); }
  async listByRevision(revisionId: string, session: StudioSession) { const item = await this.requireRevisionById(revisionId, session); return explanationsRepository.list(item.revision.id); }
  async replace(questionId: string, revisionId: string, input: ReplaceBlocks, session: StudioSession) { await this.requireEditableRevision(questionId, revisionId, session); const result = await explanationsRepository.replace(revisionId, questionId, input, session.profileId); if (input.blocks.length) await this.markExplanationDrafted(questionId, session); return result; }
  async replaceByRevision(revisionId: string, input: ReplaceBlocks, session: StudioSession) { const item = await this.requireRevisionById(revisionId, session); return this.replace(item.question.id, revisionId, input, session); }
  async add(revisionId: string, input: AddBlock, session: StudioSession) { const item = await this.requireRevisionById(revisionId, session); this.requireExplanationPermission(session); this.requireDraft(item.revision.status); const block = await explanationsRepository.add(revisionId, item.question.id, input, session.profileId); await this.markExplanationDrafted(item.question.id, session); return block; }
  async update(blockId: string, input: UpdateBlock, session: StudioSession) { const item = await explanationsRepository.findBlock(blockId); if (!item) throw new AppError({ statusCode: 404, code: "EXPLANATION_BLOCK_NOT_FOUND", message: "Explanation block not found." }); await questionsService.requireQuestionAccess(item.question.id, session); this.requireExplanationPermission(session); this.requireDraft(item.revision.status); const block = await explanationsRepository.update(blockId, item.question.id, item.revision.id, input, session.profileId); if (!block) throw new AppError({ statusCode: 404, code: "EXPLANATION_BLOCK_NOT_FOUND", message: "Explanation block not found." }); await this.markExplanationDrafted(item.question.id, session); return block; }
  async remove(blockId: string, session: StudioSession) { const item = await explanationsRepository.findBlock(blockId); if (!item) throw new AppError({ statusCode: 404, code: "EXPLANATION_BLOCK_NOT_FOUND", message: "Explanation block not found." }); await questionsService.requireQuestionAccess(item.question.id, session); this.requireExplanationPermission(session); this.requireDraft(item.revision.status); const block = await explanationsRepository.remove(blockId, item.question.id, item.revision.id, session.profileId); if (!block) throw new AppError({ statusCode: 404, code: "EXPLANATION_BLOCK_NOT_FOUND", message: "Explanation block not found." }); }
  async listReferences(revisionId: string, session: StudioSession) { const item = await this.requireRevisionById(revisionId, session); return explanationsRepository.listReferences(item.revision.id); }
  async replaceReferences(revisionId: string, input: ReplaceReferences, session: StudioSession) { const item = await this.requireRevisionById(revisionId, session); this.requireExplanationPermission(session); this.requireDraft(item.revision.status); return explanationsRepository.replaceReferences(revisionId, item.question.id, input, session.profileId); }
  private async requireRevision(questionId: string, revisionId: string, session: StudioSession) { await questionsService.requireQuestionAccess(questionId, session); const revision = await questionsRepository.findRevision(questionId, revisionId); if (!revision) throw new AppError({ statusCode: 404, code: "QUESTION_REVISION_NOT_FOUND", message: "Question revision not found." }); return revision; }
  private async requireRevisionById(revisionId: string, session: StudioSession) { const item = await questionsRepository.findByRevisionId(revisionId); if (!item) throw new AppError({ statusCode: 404, code: "QUESTION_REVISION_NOT_FOUND", message: "Question revision not found." }); await questionsService.requireQuestionAccess(item.question.id, session); return item; }
  private async requireEditableRevision(questionId: string, revisionId: string, session: StudioSession) { const revision = await this.requireRevision(questionId, revisionId, session); this.requireExplanationPermission(session); this.requireDraft(revision.status); }
  private async markExplanationDrafted(questionId: string, session: StudioSession) { const question = await questionsService.requireQuestionAccess(questionId, session); if (["NEEDS_EXPLANATION", "QUESTION_SUBMITTED"].includes(question.status)) await questionsRepository.updateQuestionStatus(questionId, "EXPLANATION_READY", session.profileId, "explanation_drafted"); }
  private requireExplanationPermission(session: StudioSession) { if (!session.permissions.includes("explanation.edit")) throw new AppError({ statusCode: 403, code: "PERMISSION_DENIED", message: "You do not have permission to edit explanations." }); }
  private requireDraft(status: string) { if (status !== "DRAFT") throw new AppError({ statusCode: 409, code: "IMMUTABLE_REVISION", message: "Only draft revisions can be edited." }); }
}

export const explanationsService = new ExplanationsService();
