import { and, asc, desc, eq, isNull } from 'drizzle-orm';
import { db } from '../../database/client.js';
import { studioAuditLog, studioComment, studioProfile, studioQuestion, studioQuestionRevision, studioReview, studioReviewQueue, studioReviewQueueItem } from '../../database/schema.js';
import type { AddComment, AssignQueue } from './review.schemas.js';
export class ReviewRepository {
  listQueue(profileId: string) { return db.select({ item: studioReviewQueueItem, question: studioQuestion, revision: studioQuestionRevision }).from(studioReviewQueueItem).innerJoin(studioQuestion, eq(studioReviewQueueItem.questionId, studioQuestion.id)).innerJoin(studioQuestionRevision, eq(studioReviewQueueItem.revisionId, studioQuestionRevision.id)).where(and(eq(studioReviewQueueItem.reviewerProfileId, profileId), eq(studioReviewQueueItem.status, 'ASSIGNED'))).orderBy(asc(studioReviewQueueItem.position), asc(studioReviewQueueItem.createdAt)); }
  async findQueue(queueId: string) { const [queue] = await db.select().from(studioReviewQueue).where(eq(studioReviewQueue.id, queueId)); return queue ?? null; }
  listQueueItems(queueId: string) { return db.select({ item: studioReviewQueueItem, question: studioQuestion, revision: studioQuestionRevision }).from(studioReviewQueueItem).innerJoin(studioQuestion, eq(studioReviewQueueItem.questionId, studioQuestion.id)).innerJoin(studioQuestionRevision, eq(studioReviewQueueItem.revisionId, studioQuestionRevision.id)).where(eq(studioReviewQueueItem.queueId, queueId)).orderBy(asc(studioReviewQueueItem.position), asc(studioReviewQueueItem.createdAt)); }
  async ensureQueue(profileId: string) { await db.insert(studioReviewQueue).values({ reviewerProfileId: profileId }).onConflictDoNothing(); const [queue] = await db.select().from(studioReviewQueue).where(eq(studioReviewQueue.reviewerProfileId, profileId)); return queue!; }
  async assign(input: AssignQueue, actorProfileId: string) { const queue = await this.ensureQueue(input.reviewerProfileId); const [item] = await db.insert(studioReviewQueueItem).values({ ...input, queueId: queue.id, position: input.position ?? 0, assignedBy: actorProfileId }).returning(); return item!; }
  async findQueueItem(id: string) { const [item] = await db.select().from(studioReviewQueueItem).where(eq(studioReviewQueueItem.id, id)); return item ?? null; }
  async decide(questionId: string, revisionId: string, profileId: string, decision: 'APPROVED' | 'CHANGES_REQUESTED', comment: string | null, isMedicalReview: boolean) { return db.transaction(async (tx) => { const [review] = await tx.insert(studioReview).values({ questionId, revisionId, reviewerProfileId: profileId, decision, comment, isMedicalReview: isMedicalReview ? 'yes' : 'no' }).returning(); if (comment) await tx.insert(studioComment).values({ questionId, revisionId, body: comment, createdBy: profileId }); await tx.update(studioQuestionRevision).set({ status: decision === 'APPROVED' ? 'APPROVED' : 'DRAFT', ...(isMedicalReview && decision === 'APPROVED' ? { medicalReviewedBy: profileId, medicalReviewedAt: new Date() } : {}) }).where(eq(studioQuestionRevision.id, revisionId)); await tx.update(studioQuestion).set({ status: decision }).where(eq(studioQuestion.id, questionId)); await tx.update(studioReviewQueueItem).set({ status: 'COMPLETED', completedAt: new Date() }).where(and(eq(studioReviewQueueItem.questionId, questionId), eq(studioReviewQueueItem.revisionId, revisionId), eq(studioReviewQueueItem.reviewerProfileId, profileId), eq(studioReviewQueueItem.status, 'ASSIGNED'))); await tx.insert(studioAuditLog).values({ questionId, revisionId, actorProfileId: profileId, action: decision === 'APPROVED' ? 'review_approved' : 'review_changes_requested', metadata: { isMedicalReview } }); return review!; }); }
  async skip(queueId: string, profileId: string) { const [item] = await db.update(studioReviewQueueItem).set({ status: 'SKIPPED', completedAt: new Date() }).where(and(eq(studioReviewQueueItem.id, queueId), eq(studioReviewQueueItem.reviewerProfileId, profileId), eq(studioReviewQueueItem.status, 'ASSIGNED'))).returning(); return item ?? null; }
  listComments(questionId: string) { return db.select({ comment: studioComment, author: { id: studioProfile.id, displayName: studioProfile.displayName, email: studioProfile.email } }).from(studioComment).innerJoin(studioProfile, eq(studioComment.createdBy, studioProfile.id)).where(eq(studioComment.questionId, questionId)).orderBy(asc(studioComment.createdAt)); }
  async addComment(questionId: string, input: AddComment, profileId: string) { const [comment] = await db.insert(studioComment).values({ questionId, ...input, createdBy: profileId }).returning(); await db.insert(studioAuditLog).values({ questionId, revisionId: input.revisionId, actorProfileId: profileId, action: 'comment_added', metadata: { commentId: comment!.id } }); return comment!; }
  async findComment(commentId: string) { const [comment] = await db.select().from(studioComment).where(eq(studioComment.id, commentId)); return comment ?? null; }
  async updateComment(commentId: string, body: string) { const [comment] = await db.update(studioComment).set({ body }).where(and(eq(studioComment.id, commentId), isNull(studioComment.deletedAt))).returning(); return comment ?? null; }
  async deleteComment(commentId: string) { const [comment] = await db.update(studioComment).set({ deletedAt: new Date() }).where(and(eq(studioComment.id, commentId), isNull(studioComment.deletedAt))).returning(); return comment ?? null; }
}
export const reviewRepository = new ReviewRepository();
