import { AppError } from '../../lib/AppError.js';
import type { StudioSession } from '../auth/auth.types.js';
import { questionsRepository } from '../questions/questions.repository.js';
import { questionsService } from '../questions/questions.service.js';
import type { AddComment, AssignQueue } from './review.schemas.js';
import { reviewRepository } from './review.repository.js';
export class ReviewService {
  async queue(session: StudioSession) { if (!session.permissions.includes('question.review')) throw this.denied(); const queue = await reviewRepository.ensureQueue(session.profileId); return { queue, items: this.withNavigation(await reviewRepository.listQueue(session.profileId)) }; }
  async queueItems(queueId: string, session: StudioSession) { const queue = await reviewRepository.findQueue(queueId); if (!queue) throw new AppError({ statusCode: 404, code: 'REVIEW_QUEUE_NOT_FOUND', message: 'Review queue not found.' }); if (queue.reviewerProfileId !== session.profileId && !session.permissions.includes('review.view_all')) throw this.denied(); return this.withNavigation(await reviewRepository.listQueueItems(queueId)); }
  async assign(input: AssignQueue, session: StudioSession) { if (!session.permissions.includes('review.assign')) throw this.denied(); const revision = await questionsRepository.findRevision(input.questionId, input.revisionId); if (!revision) throw new AppError({ statusCode: 404, code: 'QUESTION_REVISION_NOT_FOUND', message: 'Question revision not found.' }); await questionsService.requireQuestionAccess(input.questionId, session); if (revision.status !== 'DRAFT') throw new AppError({ statusCode: 409, code: 'INVALID_REVIEW_STATE', message: 'Only draft revisions can be queued for review.' }); return reviewRepository.assign(input, session.profileId); }
  async reviewReady(questionId: string, session: StudioSession) { await questionsService.requireQuestionAccess(questionId, session); return questionsRepository.details(questionId); }
  async approve(questionId: string, session: StudioSession) { return this.decide(questionId, 'APPROVED', null, session); }
  async requestChanges(questionId: string, comment: string, session: StudioSession) { return this.decide(questionId, 'CHANGES_REQUESTED', comment, session); }
  async skip(queueId: string, session: StudioSession) { if (!session.permissions.includes('question.review')) throw this.denied(); const item = await reviewRepository.skip(queueId, session.profileId); if (!item) throw new AppError({ statusCode: 404, code: 'REVIEW_QUEUE_ITEM_NOT_FOUND', message: 'Active review queue item not found.' }); return item; }
  async listComments(questionId: string, session: StudioSession) { await questionsService.requireQuestionAccess(questionId, session); return reviewRepository.listComments(questionId); }
  async addComment(questionId: string, input: AddComment, session: StudioSession) { await questionsService.requireQuestionAccess(questionId, session); if (input.revisionId && !await questionsRepository.findRevision(questionId, input.revisionId)) throw new AppError({ statusCode: 400, code: 'INVALID_COMMENT_REVISION', message: 'Comment revision must belong to the question.' }); return reviewRepository.addComment(questionId, input, session.profileId); }
  async updateComment(commentId: string, body: string, session: StudioSession) { const comment = await reviewRepository.findComment(commentId); if (!comment || comment.deletedAt) throw new AppError({ statusCode: 404, code: 'COMMENT_NOT_FOUND', message: 'Comment not found.' }); await questionsService.requireQuestionAccess(comment.questionId, session); if (comment.createdBy !== session.profileId) throw new AppError({ statusCode: 403, code: 'COMMENT_EDIT_DENIED', message: 'Only the comment author can edit it.' }); const updated = await reviewRepository.updateComment(commentId, body); if (!updated) throw new AppError({ statusCode: 404, code: 'COMMENT_NOT_FOUND', message: 'Comment not found.' }); return updated; }
  async deleteComment(commentId: string, session: StudioSession) { const comment = await reviewRepository.findComment(commentId); if (!comment || comment.deletedAt) throw new AppError({ statusCode: 404, code: 'COMMENT_NOT_FOUND', message: 'Comment not found.' }); await questionsService.requireQuestionAccess(comment.questionId, session); if (comment.createdBy !== session.profileId) throw new AppError({ statusCode: 403, code: 'COMMENT_DELETE_DENIED', message: 'Only the comment author can delete it.' }); const deleted = await reviewRepository.deleteComment(commentId); if (!deleted) throw new AppError({ statusCode: 404, code: 'COMMENT_NOT_FOUND', message: 'Comment not found.' }); }
  private async decide(questionId: string, decision: 'APPROVED' | 'CHANGES_REQUESTED', comment: string | null, session: StudioSession) { if (!session.permissions.includes('question.review')) throw this.denied(); const question = await questionsService.requireQuestionAccess(questionId, session); const details = await questionsRepository.details(questionId); if (!details) throw new AppError({ statusCode: 404, code: 'QUESTION_NOT_FOUND', message: 'Question not found.' }); const revision = details.revision; if (!['QUESTION_SUBMITTED', 'EXPLANATION_READY', 'UNDER_REVIEW'].includes(question.status)) throw new AppError({ statusCode: 409, code: 'INVALID_REVIEW_STATE', message: `Question in ${question.status} is not ready for review.` }); const isMedicalReview = revision.requiresMedicalReview === 'yes'; if (decision === 'APPROVED' && isMedicalReview && !session.permissions.includes('medical.review')) throw new AppError({ statusCode: 403, code: 'MEDICAL_REVIEW_REQUIRED', message: 'This revision requires approval by a medical reviewer.' }); return reviewRepository.decide(questionId, revision.id, session.profileId, decision, comment, isMedicalReview); }
  private denied() { return new AppError({ statusCode: 403, code: 'PERMISSION_DENIED', message: 'You do not have permission to review questions.' }); }
  private withNavigation<T extends { item: { id: string } }>(items: T[]) { return items.map((item, index) => ({ ...item, previousItemId: items[index - 1]?.item.id ?? null, nextItemId: items[index + 1]?.item.id ?? null })); }
}
export const reviewService = new ReviewService();
