"use client";

import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { getStudentPreview } from "@/lib/api/explanations";
import { getReviewQueue } from "@/lib/api/review";

export function ReviewNavigation({ questionId, queueId }: { questionId: string; queueId: string | null }) { const queue = useQuery({ queryKey: ["review", "queue"], queryFn: getReviewQueue, enabled: Boolean(queueId) }); const index = queue.data?.items.findIndex((item) => item.question.id === questionId) ?? -1; const previous = index > 0 ? queue.data?.items[index - 1] : null; const next = index >= 0 ? queue.data?.items[index + 1] : null; if (!queueId || !queue.data) return null; return <nav aria-label="Queue navigation" className="mt-4 flex justify-between text-sm"><span>{previous ? <Link className="underline" href={`/review/${previous.question.id}?queue=${queueId}`}>← Previous</Link> : "First item"}</span><span>{next ? <Link className="underline" href={`/review/${next.question.id}?queue=${queueId}`}>Next →</Link> : "Last item"}</span></nav>; }
export function ReviewExplanation({ revisionId }: { revisionId: string }) { const preview = useQuery({ queryKey: ["preview", revisionId], queryFn: () => getStudentPreview(revisionId) }); if (preview.isLoading) return <p className="text-sm text-slate-600">Loading explanation…</p>; if (preview.isError || !preview.data) return <p className="text-sm text-slate-600">No student preview is available for this revision.</p>; return <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Explanation and references</h2><div className="mt-3 space-y-2 text-sm">{preview.data.explanationBlocks.length ? preview.data.explanationBlocks.map((block) => <p key={block.id}>{typeof block.content === "string" ? block.content : JSON.stringify(block.content)}</p>) : <p className="text-slate-600">No explanation blocks yet.</p>}</div>{preview.data.references.length > 0 && <ol className="mt-4 list-decimal space-y-1 pl-5 text-sm">{preview.data.references.map((reference, index) => <li key={reference.id ?? index}><a className="underline" href={reference.sourceUrl} target="_blank" rel="noreferrer">{reference.sourceTitle}</a></li>)}</ol>}</section>; }
